services:
  app:
    container_name: smart-shell-angular
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_URL: $API_URL
      HEALTH_CHECK_URL: $HEALTH_CHECK_URL
      NGINX_DEBUG: $NGINX_DEBUG
    ports:
      - "${SMART_SHELL_ANGULAR_PORT}:80"
    networks:
      - smart-shell-net
    restart: unless-stopped

networks:
  smart-shell-net:
    external: true
