apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: smart-shell-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: luis122448/smart-shell-angular:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "/app-project"
        - name: HEALTH_CHECK_URL
          value: "/app-project/actuator/health/liveness"
        - name: NGINX_DEBUG
          value: "false"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
